server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

weather-api:
  base-url: http://api.weatherapi.com/v1
  key: 5bfe650b86b94f2a8cc150657211801
  endpoints:
    current: /current.json

resilience4j.ratelimiter:
  instances:
    weatherapi:
      limitForPeriod: 1000000
      limitRefreshPeriod: 30d
